name: dart_basics
description: Basic
version: 0.0.1
repository: https://github.com/kotertom/dart_basics

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  leancode_lint: ^4.0.0
  melos: ^3.1.0
  test: ^1.21.0
